"use client";

import { AuthProvider } from "react-oidc-context";
import { CognitoAuthConfig } from "@/lib/auth";
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; // Import Link from Next.js
import "./globals.css";
import RegisterSW from "./sw-register";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: "#000000",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider {...CognitoAuthConfig}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="p-4 bg-gray-200">
            <ul className="flex gap-4">
              <li>
                <Link href="/" className="text-blue-600 hover:underline">
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href="/admin/page-builder"
                  className="text-blue-600 hover:underline"
                >
                  Page Builder
                </Link>
              </li>
            </ul>
          </nav>

          {/* Main Content */}
          <main className="p-4">
            {children}
            <RegisterSW />
          </main>
        </body>
      </html>
    </AuthProvider>
  );
}